#!/bin/bash
# FIXME: Causes backlight to dim when launch_dashboard is triggered
## Get Brightness
#get_blight() {
#	while true; do
#  	echo "$(brightnessctl get)"
#		sleep 1
#	done
#}
#
### Set Brightness
#set_blight() {
#  brightnessctl set $1
#}
#
#
#
#if [[ "$1" == "--get" ]]; then
#	get_blight
#elif [[ "$1" == "--set" ]]; then
#	set_blight "$2"
#fi
#brightnessctl